---
spring:
  profiles: peer1 #指定profiles为peer1
  application:
      name: steven-cloud-peer1
server:
  port: 8763
eureka:
  instance:
    hostname: peer1
    prefer-ip-address: true  #显示ip地址
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/   #将自己注册到peer2
---
spring:
  profiles: peer2
  application:
        name: steven-cloud-peer1
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
    prefer-ip-address: true  #显示ip地址
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/   #将自己注册到peer1