---
spring:
  application:
    name: cloud-movie
  profiles: peer1
server:
  port: 8001
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/,http://peer1:8761/eureka/
    healthcheck:
      enabled: true #健康检查
      registry-fetch-interval-seconds: 30 #拉取服务器注册信息时间
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

---
spring:
  application:
    name: cloud-movie
  profiles: peer2
server:
  port: 8002
eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
    healthcheck:
      enabled: true #健康检查
      registry-fetch-interval-seconds: 30 #拉取服务器注册信息时间
#      java -jar steven.jar --spring.profiles.active=peer1
#mvn clean package spring-boot:repackage -Dmaven.test.skip=true