---
spring:
  profiles: peer1
  application:
    name: discover-server
server:
  port: 8761
eureka:
  instance:
    hostname: peer1
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/

---
spring:
  application:
    name: discover-server
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
    prefer-ip-address: true  #显示ip地址
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/

#      java -jar steven.jar --spring.profiles.active=peer1
#mvn clean package spring-boot:repackage -Dmaven.test.skip=true