---
server:
  port: 8761  #指定该Eureka实例的端口
spring:
  application:
    name: erueka-server
  profiles: peer1
  cloud:
    config:
      discovery:
        enabled: true
eureka:
  instance:
    hostname: peer1 # 指定该Eureka实例的主机名
    prefer-ip-address: true  #显示ip地址
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
#      defaultZone: http://peer2:8762/eureka/
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    healthcheck:
      enabled: true #健康检查
    registry-fetch-interval-seconds: 30 #拉取服务器注册信息时间

---
server:
  port: 8762  #指定该Eureka实例的端口
spring:
  application:
    name: erueka-server
  profiles: peer2
  cloud:
    config:
      discovery:
        enabled: true
eureka:
  instance:
    hostname: peer2 # 指定该Eureka实例的主机名
    prefer-ip-address: true  #显示ip地址
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
#      defaultZone: http://peer1:8761/eureka/
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    healthcheck:
      enabled: true #健康检查
    registry-fetch-interval-seconds: 30 #拉取服务器注册信息时间
